# version: '3.8'

# services:
#   qdrant:
#     image: qdrant/qdrant:latest
#     container_name: qdrant2
#     ports:
#       - "6333:6333"
#       - "6334:6334"  # gRPC port (optional)
#     volumes:
#       - qdrant_data:/qdrant/storage
#     environment:
#       - QDRANT__SERVICE__HTTP_PORT=6333
#       - QDRANT__SERVICE__GRPC_PORT=6334
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s

#   minio:
#     image: minio/minio
#     ports:
#       - "9000:9000"  # API port
#       - "9001:9001"  # Console port
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin
#     volumes:
#       - minio_data:/data
#     command: server --console-address ":9001" /data
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#       interval: 30s
#       timeout: 20s
#       retries: 3

# volumes:
#   qdrant_data:
#     driver: local
#   minio_data:

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://localhost:11434
      - QDRANT_HOST=qdrant
      - MINIO_HOST=minio
    depends_on:
      - qdrant
      - minio
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant2
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  minio_data:
    driver: local